-- Built from sources/pharmacy_catalog.csv, drug_side_effects.csv, drug_drug_interactions.csv
PRAGMA foreign_keys = ON;

CREATE TABLE drug (
  scientific_name TEXT PRIMARY KEY
);

CREATE TABLE trade_name (
  trade_name TEXT PRIMARY KEY,
  scientific_name TEXT NOT NULL,
  FOREIGN KEY (scientific_name) REFERENCES drug(scientific_name)
);

CREATE TABLE side_effect (
  effect_id INTEGER PRIMARY KEY AUTOINCREMENT,
  scientific_name TEXT NOT NULL,
  effect_text TEXT NOT NULL,
  FOREIGN KEY (scientific_name) REFERENCES drug(scientific_name)
);

CREATE TABLE interaction (
  interaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
  drug1 TEXT NOT NULL,
  drug2 TEXT NOT NULL,
  description TEXT NOT NULL,
  FOREIGN KEY (drug1) REFERENCES drug(scientific_name),
  FOREIGN KEY (drug2) REFERENCES drug(scientific_name)
);

INSERT INTO drug (scientific_name) VALUES
  ('Paracetamol'),
  ('Ibuprofen'),
  ('Warfarin'),
  ('Aspirin'),
  ('Metformin'),
  ('Atorvastatin'),
  ('Amlodipine'),
  ('Omeprazole'),
  ('Amoxicillin/Clavulanate'),
  ('Azithromycin'),
  ('Metronidazole'),
  ('Salbutamol'),
  ('Cetirizine'),
  ('Clopidogrel'),
  ('Bisoprolol'),
  ('Prednisolone'),
  ('Clarithromycin'),
  ('Lorazepam'),
  ('Simvastatin'),
  ('Lisinopril'),
  ('Levothyroxine'),
  ('Amoxicillin'),
  ('Ciprofloxacin'),
  ('Furosemide'),
  ('Pantoprazole'),
  ('Gliclazide');

INSERT INTO trade_name (trade_name, scientific_name) VALUES
  ('Panadol', 'Paracetamol'),
  ('Adol', 'Paracetamol'),
  ('Paramol', 'Paracetamol'),
  ('Brufen', 'Ibuprofen'),
  ('Nurofen', 'Ibuprofen'),
  ('Marevan', 'Warfarin'),
  ('Coumadin', 'Warfarin'),
  ('Aspirin', 'Aspirin'),
  ('Aspocid', 'Aspirin'),
  ('Glucophage', 'Metformin'),
  ('Cidophage', 'Metformin'),
  ('Lipitor', 'Atorvastatin'),
  ('Ator', 'Atorvastatin'),
  ('Norvasc', 'Amlodipine'),
  ('Amlor', 'Amlodipine'),
  ('Losec', 'Omeprazole'),
  ('Risek', 'Omeprazole'),
  ('Augmentin', 'Amoxicillin/Clavulanate'),
  ('Curam', 'Amoxicillin/Clavulanate'),
  ('Zithromax', 'Azithromycin'),
  ('Azimex', 'Azithromycin'),
  ('Flagyl', 'Metronidazole'),
  ('Flazol', 'Metronidazole'),
  ('Ventolin', 'Salbutamol'),
  ('Butalin', 'Salbutamol'),
  ('Zyrtec', 'Cetirizine'),
  ('Allerzet', 'Cetirizine'),
  ('Plavix', 'Clopidogrel'),
  ('Concor', 'Bisoprolol'),
  ('Prednisolone', 'Prednisolone'),
  ('Klacid', 'Clarithromycin'),
  ('Ativan', 'Lorazepam'),
  ('Zocor', 'Simvastatin'),
  ('Zestril', 'Lisinopril'),
  ('Euthyrox', 'Levothyroxine'),
  ('Amoxil', 'Amoxicillin'),
  ('Ciproxin', 'Ciprofloxacin'),
  ('Lasix', 'Furosemide'),
  ('Controloc', 'Pantoprazole'),
  ('Diamicron', 'Gliclazide');

INSERT INTO side_effect (scientific_name, effect_text) VALUES
  ('Paracetamol', 'Nausea'),
  ('Paracetamol', 'Skin rash'),
  ('Paracetamol', 'Liver harm if the dose is too high'),
  ('Ibuprofen', 'Stomach burn'),
  ('Ibuprofen', 'Headache'),
  ('Ibuprofen', 'Higher chance of bleeding'),
  ('Warfarin', 'Bleeding'),
  ('Warfarin', 'Bruises'),
  ('Warfarin', 'Many drug interactions'),
  ('Aspirin', 'Stomach pain'),
  ('Aspirin', 'Bleeding'),
  ('Aspirin', 'Allergy in some people'),
  ('Metformin', 'Diarrhea'),
  ('Metformin', 'Metallic taste'),
  ('Metformin', 'Nausea'),
  ('Atorvastatin', 'Muscle pain'),
  ('Atorvastatin', 'Headache'),
  ('Atorvastatin', 'Stomach upset'),
  ('Amlodipine', 'Swollen feet'),
  ('Amlodipine', 'Headache'),
  ('Amlodipine', 'Flushed face'),
  ('Omeprazole', 'Headache'),
  ('Omeprazole', 'Gas'),
  ('Omeprazole', 'Stomach pain'),
  ('Amoxicillin/Clavulanate', 'Diarrhea'),
  ('Amoxicillin/Clavulanate', 'Rash'),
  ('Amoxicillin/Clavulanate', 'Nausea'),
  ('Azithromycin', 'Diarrhea'),
  ('Azithromycin', 'Stomach pain'),
  ('Azithromycin', 'Nausea'),
  ('Metronidazole', 'Metallic taste'),
  ('Metronidazole', 'Nausea'),
  ('Metronidazole', 'Do not take with alcohol'),
  ('Salbutamol', 'Shaking'),
  ('Salbutamol', 'Fast heartbeat'),
  ('Salbutamol', 'Headache'),
  ('Cetirizine', 'Sleepiness'),
  ('Cetirizine', 'Dry mouth'),
  ('Cetirizine', 'Headache'),
  ('Clopidogrel', 'Bleeding'),
  ('Clopidogrel', 'Bruises'),
  ('Clopidogrel', 'Stomach upset'),
  ('Bisoprolol', 'Tiredness'),
  ('Bisoprolol', 'Slow heartbeat'),
  ('Bisoprolol', 'Cold hands'),
  ('Prednisolone', 'Stomach upset'),
  ('Prednisolone', 'Mood change'),
  ('Prednisolone', 'Higher blood sugar'),
  ('Clarithromycin', 'Taste change'),
  ('Clarithromycin', 'Diarrhea'),
  ('Clarithromycin', 'Stomach pain'),
  ('Lorazepam', 'Sleepiness'),
  ('Lorazepam', 'Unsteady walk'),
  ('Lorazepam', 'Memory problems'),
  ('Simvastatin', 'Muscle pain'),
  ('Simvastatin', 'Headache'),
  ('Simvastatin', 'Stomach upset'),
  ('Lisinopril', 'Dry cough'),
  ('Lisinopril', 'Dizziness'),
  ('Lisinopril', 'High potassium'),
  ('Levothyroxine', 'Heart palpitations'),
  ('Levothyroxine', 'Sweating'),
  ('Levothyroxine', 'Weight loss'),
  ('Amoxicillin', 'Diarrhea'),
  ('Amoxicillin', 'Rash'),
  ('Amoxicillin', 'Nausea'),
  ('Ciprofloxacin', 'Nausea'),
  ('Ciprofloxacin', 'Tendon pain'),
  ('Ciprofloxacin', 'Dizziness'),
  ('Furosemide', 'Passing urine often'),
  ('Furosemide', 'Low potassium'),
  ('Furosemide', 'Dizziness'),
  ('Pantoprazole', 'Headache'),
  ('Pantoprazole', 'Diarrhea'),
  ('Pantoprazole', 'Stomach pain'),
  ('Gliclazide', 'Low blood sugar'),
  ('Gliclazide', 'Weight gain'),
  ('Gliclazide', 'Nausea');

INSERT INTO interaction (drug1, drug2, description) VALUES
  ('Ibuprofen', 'Warfarin', 'The risk or severity of bleeding can be increased when Ibuprofen is combined with Warfarin.'),
  ('Aspirin', 'Warfarin', 'The risk or severity of bleeding can be increased when Aspirin is combined with Warfarin.'),
  ('Ibuprofen', 'Aspirin', 'The therapeutic efficacy of Aspirin can be decreased when used in combination with Ibuprofen.'),
  ('Metronidazole', 'Warfarin', 'The risk or severity of bleeding can be increased when Metronidazole is combined with Warfarin.'),
  ('Azithromycin', 'Warfarin', 'The serum concentration of Warfarin can be increased when it is combined with Azithromycin.'),
  ('Amlodipine', 'Atorvastatin', 'The metabolism of Atorvastatin can be decreased when combined with Amlodipine.'),
  ('Omeprazole', 'Warfarin', 'The serum concentration of Warfarin can be increased when it is combined with Omeprazole.'),
  ('Paracetamol', 'Warfarin', 'The risk or severity of adverse effects can be increased when Paracetamol is combined with Warfarin.'),
  ('Clopidogrel', 'Omeprazole', 'The serum concentration of the active metabolites of Clopidogrel can be reduced when it is combined with Omeprazole.'),
  ('Clopidogrel', 'Aspirin', 'The risk or severity of bleeding can be increased when Clopidogrel is combined with Aspirin.'),
  ('Prednisolone', 'Aspirin', 'The risk or severity of gastrointestinal bleeding can be increased when Prednisolone is combined with Aspirin.'),
  ('Bisoprolol', 'Amlodipine', 'Bisoprolol may increase the hypotensive activities of Amlodipine.'),
  ('Metformin', 'Prednisolone', 'The therapeutic efficacy of Metformin can be decreased when used in combination with Prednisolone.'),
  ('Ibuprofen', 'Prednisolone', 'The risk or severity of gastrointestinal irritation can be increased when Ibuprofen is combined with Prednisolone.'),
  ('Atorvastatin', 'Clarithromycin', 'The serum concentration of Atorvastatin can be increased when it is combined with Clarithromycin.'),
  ('Warfarin', 'Amoxicillin/Clavulanate', 'The risk or severity of bleeding can be increased when Amoxicillin/Clavulanate is combined with Warfarin.'),
  ('Cetirizine', 'Lorazepam', 'Cetirizine may increase the central nervous system depressant activities of Lorazepam.'),
  ('Salbutamol', 'Bisoprolol', 'The therapeutic efficacy of Salbutamol can be decreased when used in combination with Bisoprolol.');
